# Generated by Django 4.1.7 on 2023-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('won', 'Won'), ('pound', 'Pound'), ('euro', 'Euro'), ('usd', 'Dollar')], max_length=5),
        ),
    ]
