# Generated by Django 4.1.7 on 2023-05-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_name_alter_amenity_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(default='London', max_length=80),
        ),
        migrations.AlterField(
            model_name='room',
            name='country',
            field=models.CharField(default='UK', max_length=50),
        ),
    ]
